### PR TITLE
Vanilla-ish Tatar Translation!

### PR DESCRIPTION
**Pull request by Amirhan-Taipovjan-Greatest-I**

### CODE REVIEW

**Comment by TheCSDev** [comment]
Heya!
Thanks a lot for the translations here as well. Currently working on rewriting this API for `1.20.x`, so some stuff may change, but the translations are definitely gonna be useful regardless. Thanks again.

**Comment by TheCSDev** [comment]
Finished porting the player badge system and the commands to the `v3.0` that is still a work in progress. The translations didn't change, so I'll merge these and use them in `v3.0` if you don't mind.

**Comment by TheCSDev** [comment]
I have a question @Amirhan-Taipovjan-Greatest-I

I have next to finished writing `v3.x` for this project. I also plan on distributing `v3.x` under the `LGPL` license. This means I will have to make a switch from `MIT` to `LGPL`. This on its own shouldn't be an issue, but when a project contains contributed assets (aka translations from you in this case), that are protected by intellectual property laws (aka Copyright in this case), it gets tricky, as in some instances, consent may be required to make a license switch.

For this reason, I'd like to first ask if you're okay with your translations being re-distrubuted under the `LGPL` license. If not, then my only opion (legally speaking, as far as I know) would be to remove any contributed assets stopping me from making that switch.

Please do let me know if you're okay with this project switching to [LGPL](https://www.gnu.org/licenses/lgpl-3.0.en.html).
One more note, I will ask my contributors the same question on the [Better Stats](https://github.com/TheCSMods/mc-better-stats) repository as well, as I plan on writing `betterstats-v3.x` and switching it to `LGPL` as well.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> I have a question @Amirhan-Taipovjan-Greatest-I
> 
> I have next to finished writing `v3.x` for this project. I also plan on distributing `v3.x` under the `LGPL` license. This means I will have to make a switch from `MIT` to `LGPL`. This on its own shouldn't be an issue, but when a project contains contributed assets (aka translations from you in this case), that are protected by intellectual property laws (aka Copyright in this case), it gets tricky, as in some instances, consent may be required to make a license switch.
> 
> For this reason, I'd like to first ask if you're okay with your translations being re-distrubuted under the `LGPL` license. If not, then my only opion (legally speaking, as far as I know) would be to remove any contributed assets stopping me from making that switch.
> 
> Please do let me know if you're okay with this project switching to [LGPL](https://www.gnu.org/licenses/lgpl-3.0.en.html).
> One more note, I will ask my contributors the same question on the [Better Stats](https://github.com/TheCSMods/mc-better-stats) repository as well, as I plan on writing `betterstats-v3.x` and switching it to `LGPL` as well.


Hello! As the translation contributor for Tcdcommons and Better Stats... I fully agree that You can use My translations!

**Pull request merged**
